import { notFound } from 'next/navigation';
import { cities, bySlug, money } from '../../data/cities';

const pairs=[['greenville','charleston'],['greenville','columbia'],['lexington','fort-mill'],['lexington','bluffton'],['charleston','bluffton'],['columbia','lexington']];
const guides={
 'moving-to-south-carolina':['Moving to South Carolina','A practical starting point for understanding the state before you choose a city.'],
 'best-places-to-live-south-carolina':['Best Places to Live in South Carolina','There is no single best place. The useful question is which place best fits your priorities.'],
 'choosing-schools-in-south-carolina':['How to Research Schools Before Moving','Use address-level assignments and official report cards rather than a single citywide score.'],
 'south-carolina-property-taxes':['Understanding South Carolina Property Taxes','Property tax is local, so use county resources instead of relying on one statewide percentage.'],
 'south-carolina-relocation-checklist':['South Carolina Relocation Checklist','A simple sequence for narrowing where to live and validating the choice in person.']
};
const localCats=['restaurants','movers','cleaning','hvac','plumbing','electricians','roofing','landscaping'];

function Explore(){return <><section className="pageHero"><div className="container"><div className="eyebrow">Explore</div><h1>South Carolina communities</h1><p>Our launch set is intentionally small. We would rather publish six useful profiles than sixty thin ones.</p></div></section><section className="section alt"><div className="container grid3">{cities.map(c=><a className="card" href={`/cities/${c.slug}`} key={c.slug}><div className="region">{c.region}</div><h3>{c.name}</h3><p>{c.summary}</p><div className="data3"><div className="datum"><small>Population</small><b>{c.population.toLocaleString()}</b></div><div className="datum"><small>Median home</small><b>{money(c.home)}</b></div><div className="datum"><small>Income</small><b>{money(c.income)}</b></div></div></a>)}</div></section></>}
function City({c}){return <><section className="pageHero"><div className="container"><div className="eyebrow">{c.region} · City Guide</div><h1>{c.name}, South Carolina</h1><p>{c.summary}</p><div className="tags">{c.best.map(t=><span className="tag" key={t}>{t}</span>)}</div></div></section><section className="section alt"><div className="container profile"><article className="prose"><div className="notice">Sourced facts and Hometown Guidebook editorial analysis are intentionally separated.</div><h2>The quick read</h2><p>{c.summary}</p><h2>Housing and cost context</h2><p>Census QuickFacts reports a median owner-occupied housing value of <strong>{money(c.home)}</strong> and median gross rent of <strong>{money(c.rent)}</strong> for the current profile period.</p><h2>Who it may fit best</h2><ul>{c.best.map(x=><li key={x}>{x}</li>)}</ul><h2>Main tradeoffs</h2><ul>{c.trade.map(x=><li key={x}>{x}</li>)}</ul><h2>Source standard</h2><p>Population, housing, income and commute figures should be sourced to the U.S. Census Bureau. School, airport and tax references should point to official local or state sources.</p></article><aside><div className="sidebox"><h3>At a glance</h3><div className="fact"><span>Population</span><b>{c.population.toLocaleString()}</b></div><div className="fact"><span>Growth</span><b>{c.growth}%</b></div><div className="fact"><span>Median home</span><b>{money(c.home)}</b></div><div className="fact"><span>Median rent</span><b>{money(c.rent)}</b></div><div className="fact"><span>Median income</span><b>{money(c.income)}</b></div><div className="fact"><span>Commute</span><b>{c.commute} min</b></div></div></aside></div></section></>}
function CompareIndex(){return <><section className="pageHero"><div className="container"><div className="eyebrow">Compare</div><h1>See the tradeoffs side by side.</h1><p>Consistent comparisons make it easier to decide which communities deserve a closer look.</p></div></section><section className="section alt"><div className="container grid3">{pairs.map(([a,b])=><a className="card" key={`${a}-${b}`} href={`/compare/${a}-vs-${b}`}><div className="region">Comparison</div><h3>{bySlug[a].name} vs. {bySlug[b].name}</h3><p>Housing, income, commute and lifestyle tradeoffs.</p></a>)}</div></section></>}
function Compare({a,b}){const x=bySlug[a],y=bySlug[b];if(!x||!y)notFound();const rows=[['Population',x.population.toLocaleString(),y.population.toLocaleString()],['Growth',`${x.growth}%`,`${y.growth}%`],['Median home',money(x.home),money(y.home)],['Median rent',money(x.rent),money(y.rent)],['Median income',money(x.income),money(y.income)],['Commute',`${x.commute} min`,`${y.commute} min`]];return <><section className="pageHero"><div className="container"><div className="eyebrow">Place Comparison</div><h1>{x.name} vs. {y.name}</h1><p>Start with sourced data, then decide which lifestyle tradeoffs matter more to you.</p></div></section><section className="section alt"><div className="container"><div className="grid3"><div className="card"><strong>Factor</strong></div><div className="card"><strong>{x.name}</strong></div><div className="card"><strong>{y.name}</strong></div>{rows.flatMap(([l,v1,v2])=>[<div className="card" key={l+'l'}>{l}</div>,<div className="card" key={l+'1'}>{v1}</div>,<div className="card" key={l+'2'}>{v2}</div>])}</div></div></section></>}
function Guides(){return <><section className="pageHero"><div className="container"><div className="eyebrow">Guides</div><h1>Practical relocation guides</h1><p>Useful answers to the questions that come up before you move.</p></div></section><section className="section alt"><div className="container grid3">{Object.entries(guides).map(([slug,[title,desc]])=><a className="card" href={`/guides/${slug}`} key={slug}><div className="region">Guide</div><h3>{title}</h3><p>{desc}</p></a>)}</div></section></>}
function Guide({slug}){const g=guides[slug];if(!g)notFound();return <><section className="pageHero"><div className="container"><div className="eyebrow">Relocation Guide</div><h1>{g[0]}</h1><p>{g[1]}</p></div></section><section className="section alt"><div className="container prose"><h2>The short version</h2><p>{g[1]} Hometown Guidebook’s approach is to reduce false precision: use primary sources for facts and clearly label interpretation.</p><h2>Useful official sources</h2><ul><li>U.S. Census Bureau QuickFacts</li><li>South Carolina School Report Cards</li><li>South Carolina Department of Revenue property-tax resources</li></ul></div></section></>}
function Local(){return <><section className="pageHero"><div className="container"><div className="eyebrow">Local Guide</div><h1>Once you choose a place, live there better.</h1><p>Restaurants and trusted home-service categories belong on the same platform without overwhelming the relocation experience.</p></div></section><section className="section alt"><div className="container grid3">{localCats.map(x=><a className="card" href={`/local/${x}`} key={x}><h3>{x.replace('-',' ').replace(/^./,m=>m.toUpperCase())}</h3><p>Verified local listings will live here.</p></a>)}</div></section></>}
function LocalCat({cat}){if(!localCats.includes(cat))notFound();return <><section className="pageHero"><div className="container"><div className="eyebrow">Local Guide</div><h1>{cat.replace('-',' ').replace(/^./,m=>m.toUpperCase())}</h1><p>This category is structurally ready for verified businesses.</p></div></section><section className="section alt"><div className="container"><div className="notice">No fake listings are shown. Sponsored placement will be clearly disclosed and separated from editorial recommendation.</div></div></section></>}
function Methodology(){return <><section className="pageHero"><div className="container"><div className="eyebrow">Methodology</div><h1>How Hometown Guidebook earns trust.</h1><p>Facts are sourced. Editorial judgment is labeled. Sponsored placement never secretly buys a ranking.</p></div></section><section className="section alt"><div className="container grid3"><div className="card"><h3>Primary sources first</h3><p>Census, state agencies, school districts and local governments take priority.</p></div><div className="card"><h3>Facts ≠ opinion</h3><p>Objective data and editorial analysis are kept distinct.</p></div><div className="card"><h3>Transparent matching</h3><p>The final scoring model will publish categories, weights and update cadence.</p></div></div></section></>}

export default async function CatchAll({params}){const p=(await params).slug||[];if(p[0]==='explore'&&p.length===1)return <Explore/>;if(p[0]==='cities'&&p[1])return <City c={bySlug[p[1]]||notFound()}/>;if(p[0]==='compare'&&p.length===1)return <CompareIndex/>;if(p[0]==='compare'&&p[1]){const pair=p[1].split('-vs-');return <Compare a={pair[0]} b={pair[1]}/>};if(p[0]==='guides'&&p.length===1)return <Guides/>;if(p[0]==='guides'&&p[1])return <Guide slug={p[1]}/>;if(p[0]==='local'&&p.length===1)return <Local/>;if(p[0]==='local'&&p[1])return <LocalCat cat={p[1]}/>;if(p[0]==='methodology')return <Methodology/>;notFound()}
