import { getCities } from '../data/supabase';
import { money } from '../data/cities';

export default async function Home(){
  const cities = await getCities();
  return <main>
    <section className="hero"><div className="container heroGrid">
      <div><div className="eyebrow">Where to live, made clearer</div><h1>Find the place that fits your life.</h1><p className="lead">Moving research gets messy fast. Hometown Guidebook brings housing, commute, schools, lifestyle tradeoffs and official sources together so you can compare places before you start choosing houses.</p><div className="actions"><a className="btn btnPrimary" href="/quiz">Find My Hometown</a><a className="btn" href="/explore">Explore South Carolina</a></div></div>
      <div className="heroPanel"><h2 className="panelTitle">Start with the decision, not the listing.</h2><p>A great house in the wrong place is still the wrong move. Start by narrowing the communities that fit your priorities, then investigate neighborhoods, schools, commute and housing at the address level.</p><a className="textLink" href="/methodology">See how we research places →</a></div>
    </div></section>
    <section className="section"><div className="container"><div className="sectionHead"><div><h2>South Carolina city guides</h2><p>Six starting points with very different tradeoffs, from walkable Upstate living to the Lowcountry coast and family-focused Charlotte suburbs.</p></div><a className="textLink" href="/explore">Explore all guides →</a></div><div className="grid3">{cities.map(c=><a className="card" href={`/south-carolina/${c.slug}`} key={c.slug}><div className="region">{c.region}</div><h3>Living in {c.name}, SC</h3><p>{c.summary}</p><div className="data3"><div className="datum"><small>Population</small><b>{c.population.toLocaleString()}</b></div><div className="datum"><small>Median home value</small><b>{money(c.home)}</b></div><div className="datum"><small>Mean commute</small><b>{c.commute} min</b></div></div><span className="textLink">Read the guide →</span></a>)}</div></div></section>
    <section className="section alt"><div className="container"><div className="sectionHead"><div><h2>Research the move from three angles</h2><p>Use the site in whatever order matches where you are in the decision.</p></div></div><div className="grid3"><a className="card" href="/quiz"><div className="region">01 · Match</div><h3>Start with your priorities</h3><p>Weight budget, schools, downtown activity, airport access, outdoors and other factors to build a shortlist worth researching.</p></a><a className="card" href="/compare"><div className="region">02 · Compare</div><h3>Put the tradeoffs side by side</h3><p>Compare consistent public data, then dig into the differences that averages cannot capture.</p></a><a className="card" href="/guides"><div className="region">03 · Verify</div><h3>Check what changes by address</h3><p>School assignments, property taxes and daily commute can change block by block. Our guides point you toward the right official sources.</p></a></div></div></section>
    <section className="section"><div className="container"><div className="editorialCallout"><div><div className="eyebrow">A different kind of relocation site</div><h2>Useful enough to make a decision, transparent enough to trust.</h2></div><p>We use public data as a starting point, not a substitute for local context. When something is our judgment, we label it. When a fact can change, we point to the source. And when sponsored listings arrive, they will not secretly buy editorial rankings.</p></div></div></section>
  </main>
}
